LaunchED/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('course.urls')),
    path('admin/', admin.site.urls),
]

course/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('courses/', views.courses),
    path('instructors/', views.instructors),
    path('login/', views.login),
    path('logout/', views.logout),
    path('registerStudent/', views.registerStudent),
    path('registerInstructor/', views.registerInstructor),
    path('profile/',views.profile),
    path('profile/createCourse/',views.createCourse),
    path('profile/<int:course_id>/',views.deleteStudentCourse),
    path('profile/createCourse/<int:course_id>/',views.deleteInstructorCourse),
    path('profile/profileDelete/',views.profileDelete),
    path('profile/profileUpdate/',views.profileUpdate),
    path('profile/myCourses',views.myCourse),
    path('courses/<int:course_id>/', views.enroll),
    path('sampleCertificate/',views.sampleCertificate),
    path('termsOfUse/',views.termsOfUse),
    path('contactUs/',views.contactUs),
]

course/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.db.models.deletion import CASCADE
from django.contrib.auth.decorators import *
from django.contrib.auth.models import AbstractUser, User
#from django.db.models import Q
#from datetime import time

# Create your models here.
SEX_CHOICE = [
    ('MALE', 'Male'),
    ('FEMALE', 'Female'),
    ('OTHER', 'Other'),
]

YEAR_IN_SCHOOL = [
    ('FR', 'Freshman'),
    ('SO', 'Sophomore'),
    ('JR', 'Junior'),
    ('SR', 'Senior'),
    ('GR', 'Graduate'),
]

INSTRUCTOR_QUALIFICATIONS = [
    ('TA', 'Teaching Assistant'),
    ('RA', 'Research Assistant'),
    ('AP', 'Assistant Professor'),
    ('SP', 'Senior Professor'),
    ('GR', 'Graduate'),
]

class User(AbstractUser):
    def is_student(self):
        if Student.objects.filter(email=self.email).exists():
            return True
        return False
    def is_instructor(self):
        if Instructor.objects.filter(email=self.email).exists():
            return True
        return False
    def enrolled_course_number(self):
        return StudentCourse.objects.filter(student__email__startswith=self.username).count()
    def course_number(self):
        return Course.objects.all().count()
    def inst_course(self):
        instructor = Instructor.objects.get(email=self.username)
        return instructor.course_set.all().count()

class Certifier(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return ('Name: '+ self.name + '  ,  ' + 'Certifier id: ' + str(self.id))

class Instructor(models.Model):
    sex = models.CharField(max_length=50, choices=SEX_CHOICE, null=False)
    fname = models.CharField(max_length=100,null=False)
    lname = models.CharField(max_length=100,blank=True)
    DOB = models.DateField(default='1900-01-01')
    qualification = models.CharField(max_length=2, choices=INSTRUCTOR_QUALIFICATIONS, default='GR', null=False)
    description = models.CharField(max_length=500)
    date_joined = models.DateField(default=datetime.date.today)
    email = models.EmailField(max_length=50,null=False)

    class Meta:
        unique_together = ('email', 'fname','lname')
        
    def age(self):
        dob = self.DOB
        tod = datetime.date.today()
        my_age = (tod.year - dob.year) - int((tod.month, tod.day) < (dob.month, dob.day))
        return my_age

    def __str__(self):
        return self.fname + ' ' + self.lname

class Course(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    publish_date = models.DateTimeField(default=timezone.now)
    certifier = models.ForeignKey(Certifier, on_delete=CASCADE)
    instructor = models.ForeignKey(Instructor,on_delete=CASCADE)
        
    class Meta:
        unique_together = ('name', 'instructor',)
    
    def __str__(self):
        return ("Course Name: "+self.name+" , "+"Course Instructor: "+self.instructor.fname+" "+self.instructor.lname)

class Student(models.Model):
    fname = models.CharField(max_length=100,null=False)
    lname = models.CharField(max_length=100,blank=True)
    email = models.EmailField(max_length=50,null=False)
    DOB = models.DateField(default='1980-01-01')
    datejoined = models.DateField(default=datetime.date.today)
    qualification = models.CharField(max_length=2, choices=YEAR_IN_SCHOOL, default=None, null=False)
    sex = models.CharField(max_length=50, choices=SEX_CHOICE, default=None, null=False)
    
    class Meta:
        unique_together = ('email', 'fname','lname')
    
    def age(self):
        dob = self.DOB
        tod = datetime.date.today()
        my_age = (tod.year - dob.year) - int((tod.month, tod.day) < (dob.month, dob.day))
        return my_age

    def __str__(self):
        return ("Student Name: "+ self.fname + ' ' + self.lname + ' , ' + "Student EmailID: "+ self.email)

class StudentCourse(models.Model):
    course = models.ForeignKey(Course, on_delete=CASCADE)
    student = models.ForeignKey(Student, on_delete=CASCADE)
    join_date = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('course', 'student',)

    def __str__(self):
        return ("Course Name: "+ self.course.name + ' , ' + "Student Name: " + self.student.fname + ' ' + self.student.lname)



course/views.py
from django.http import request
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import auth
from .models import Course, Instructor, Certifier, Student, StudentCourse, User

USER = get_user_model()

def dateConvert(date):
    toConvert = date.split('/')
    return( toConvert[2]+'-'+toConvert[0]+'-'+toConvert[1])

# Create your views here.
def home(request):
    return render(request,"home.html")

def courses(request):
    course = Course.objects.all() 
    COURSE = {
        "courses":course 
    }
    return render(request, 'courses.html',COURSE)

def instructors(request):
    instructor = Instructor.objects.all()
    course = Course.objects.all()
    INSTRUCTOR = {
        "instructors":instructor,
        "courses":course
    }
    return render(request, 'instructors.html',INSTRUCTOR)

def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            name = str(request.user.first_name)+" "+str(request.user.last_name)
            messages.success(request,"Successfully logged in as %s!" %name)
            return redirect('/')
        else:
            messages.success(request,"Incorrect credentials, Try again!")
            return render(request,'login.html')
    else:
        return render(request, 'login.html')

@login_required
def logout(request):
    auth.logout(request)
    messages.success(request,"You have successfully logged off!")
    return redirect("/")

def registerStudent(request):
    if request.method == "POST":
        f_name = request.POST.get('fname')
        l_name = request.POST.get('lname')
        username = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        DOB = request.POST.get('DOB')
        qual = request.POST.get('qualification')
        sex = request.POST.get('sex')
        if password1 == password2:
            DOB = dateConvert(DOB)
            user_form = USER.objects.create_user(username=username,password=password1,email=username,first_name=f_name,last_name=l_name)
            form = Student.objects.create(fname=f_name,lname=l_name,email=username,qualification=qual,sex=sex,DOB=DOB)
            user_form.save()
            form.save()
            messages.success(request,"Succesfully registered as Student! you can Sign in now")
            return redirect('/')
        else:
            messages.success(request,"Error in credentials! please re-enter values")
            return redirect('registerStudent')
    else:
        return render(request,'registerStudent.html')

def registerInstructor(request):
    if request.method == "POST":
        f_name = request.POST.get('fname')
        l_name = request.POST.get('lname')
        username = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        DOB = request.POST.get('DOB')
        qual = request.POST.get('qualification')
        sex = request.POST.get('sex')
        if password1 == password2:
            DOB = dateConvert(DOB)
            user_form = USER.objects.create_user(username=username,password=password1,email=username,first_name=f_name,last_name=l_name)
            form = Instructor.objects.create(fname=f_name,lname=l_name,email=username,qualification=qual,sex=sex,DOB=DOB)
            user_form.save()
            form.save()
            messages.success(request,"Succesfully registered as Instructor! you can Sign in now")
            return redirect('/')
        else:
            messages.success(request,"Error in credentials! please re-enter values")
            return redirect('registerInstructor')
    else:
        return render(request, 'registerInstructor.html')

@login_required
def profile(request):
    if request.user.is_student():
        student = Student.objects.get(email = request.user.username)
        courses = Course.objects.all()
        enrolled_courses = StudentCourse.objects.filter(student__email__startswith=request.user.username)
        context = {
            "Students": student,
            "Courses": courses,
            "enrolled": enrolled_courses,
        }
        return render(request,"profile.html",context)
    if request.user.is_instructor():
        instructor = Instructor.objects.get(email = request.user.username)
        courses = instructor.course_set.all()
        context = {
            "Instructors":instructor,
            "courses" : courses
        }
        return render(request,"profile.html", context)

@login_required
def deleteStudentCourse(request, course_id):
    course = StudentCourse.objects.get(pk=course_id)
    course.delete()
    return redirect('/profile')

@login_required
def profileDelete(request):
    if request.user.is_student():
        student=Student.objects.get(email = request.user.username)
        UsEr = User.objects.get(username = request.user.username)
        student.delete()
        UsEr.delete()
    if request.user.is_instructor():
        instructor=Instructor.objects.get(email = request.user.username)
        UsEr = User.objects.get(username = request.user.username)
        instructor.delete()
        UsEr.delete()
    messages.success(request,"Account successfully deleted, We're really sorry to see you leave us :'(  ")
    return redirect('/')

@login_required
def profileUpdate(request):
    if request.method == "POST":
        if request.user.is_student():
            curr_user=Student.objects.filter(email = request.user.username)
        if request.user.is_instructor():
            curr_user=Instructor.objects.filter(email = request.user.username)
        f_name = request.POST.get('fname')
        l_name = request.POST.get('lname')
        DOB = request.POST.get('DOB')
        qual = request.POST.get('qualification')
        if request.user.is_instructor():
            About = request.POST.get('About')
        if (len(DOB) == 0):
            messages.success(request,"DOB field cannot be empty!")
            return redirect('profileUpdate')
        else:
            DOB = dateConvert(DOB)
            form = curr_user.update(fname=f_name,lname=l_name,qualification=qual,DOB=DOB)
            if request.user.is_instructor():
                curr_user.update(description = About)
            form_user = USER.objects.filter(username = request.user.username)
            form_user.update(first_name=f_name, last_name=l_name)
            messages.success(request,"Successfully changed profile details")
            return redirect('/')
    else:
        return render(request,'profileUpdate.html')

@login_required
def createCourse(request):
    certifier = Certifier.objects.all()
    instructor = Instructor.objects.get(email = request.user.username)
    courses = instructor.course_set.all()
    context = {
            "certifier" : certifier,
            "Instructors":instructor,
            "courses" : courses
        }
    if request.method == "POST":
        course_name = request.POST.get('Cname')
        certifier = request.POST.get('Ccertifier')
        course_description = request.POST.get('Cdesc')
        if(len(course_name) == 0 and len(course_description) == 0):
            messages.success(request,"Invalid form, Please fill everyblock!")
            return redirect('createCourse')
        else:
            certifier_name = Certifier.objects.get(id=certifier)
            inst_name = Instructor.objects.get(email=request.user.username)
            form = Course.objects.create(name=course_name,description=course_description,certifier=certifier_name,instructor=inst_name)
            form.save()
        return redirect('/profile')

    return render(request,"createCourse.html",context)

@login_required
def deleteInstructorCourse(request, course_id):
    course = Course.objects.get(pk=course_id)
    course.delete()
    return redirect('/profile')

@login_required
def myCourse(request):
    student = Student.objects.get(email = request.user.username)
    courses = Course.objects.all()
    enrolled_courses = StudentCourse.objects.filter(student__email__startswith=request.user.username)
    context = {
            "Students": student,
            "Courses": courses,
            "enrolled": enrolled_courses,
        }
    if request.method == "POST":
        course_name = request.POST.get('Cname')
        c_id = Course.objects.get(id=course_name)
        s_name= Student.objects.get(email=request.user.username)
    return render(request,"myCourses.html",context)

@login_required
def enroll(request, course_id):
    course_id = Course.objects.get(id=course_id)
    student_id = Student.objects.get(email = request.user.username)
    if student_id.studentcourse_set.filter(course__id__contains=course_id.id).exists() == True:
        messages.success(request,"You are already enrolled in this course! select another one!")
        return redirect('/courses')
    else:
        form = StudentCourse.objects.create(course=course_id,student=student_id)
        form.save()
        return redirect('/profile')

def sampleCertificate(request):
    return render(request, "sampleCertificate.html")

def termsOfUse(request):
    return render(request, "termsOfUse.html")

def contactUs(request):
    return render(request, "contactUs.html")





templates/createCourse.html
<!--

=========================================================
* Neumorphism UI - v1.0.0
=========================================================

* Product Page: https://themesberg.com/product/ui-kits/neumorphism-ui
* Copyright 2020 Themesberg MIT LICENSE (https://www.themesberg.com/licensing#mit)

* Coded by https://themesberg.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>LaunchED - Add Course</title>

    <!--Favicon-->
    <link rel="apple-touch-icon" sizes="120x120" href="../static/images/white-favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../static/images/white-favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../static/images/white-favicon/favicon-16x16.png">
    <link rel="manifest" href="../static/images/white-favicon/site.webmanifest">

    <!-- Fontawesome -->
    <link type="text/css" href="../../static/vendor/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">

    <!-- Pixel CSS -->
    <link type="text/css" href="../../static/css/neumorphism.css" rel="stylesheet">
</head>

<body>
    <!-- HEADER -->
    <header class="header-global">
        <nav id="navbar-main" aria-label="Primary navigation"
            class="navbar navbar-main navbar-expand-lg navbar-theme-primary headroom navbar-light">
            <div class="container position-relative">
                <a href="/" class="btn btn-primary" style="color:black; font-weight:bold"></i> LaunchED</a>
                <div class="d-flex align-items-center">
                    <a href="../../logout" class="btn btn-primary text-secondary mr-3"><i
                            class="fas fa-sign-out-alt"></i> Log out</a>
                </div>
            </div>
        </nav>
    </header>
    <!-- END OF HEADER -->
    <main>
        <!-- Form Section -->
        <section class="min-vh-100 d-flex bg-primary align-items-center">
            <!--ALERT-->
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info alert-dismissible shadow-soft fade show" role="alert">
                <span class="alert-inner--icon"><span class="far fa-bell"></span></span>
                <span class="alert-inner--text"><strong>{{message}}</strong></span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}
            <!--END OF ALERT-->
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-8 col-lg-6 justify-content-center">
                        <div class="card bg-primary shadow-soft border-light p-4">
                            <div class="card-header text-center pb-0">
                                <h2 class="mb-0 h5">Create Instructor Account</h2>
                            </div>
                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <!-- Form -->
                                    <div class="form-group">
                                        <label for="exampleInputIcon4">Course Name</label>
                                        <div class="input-group mb-4">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><span
                                                        class="fas fa-book-reader mr-2"></span></span>
                                            </div>
                                            <input class="form-control" name="Cname" placeholder="Course Name"
                                                type="text" aria-label="first name">
                                        </div>
                                    </div>
                                    <!-- End of Form -->
                                    <!-- Form -->
                                    <div class="form-group">
                                        <label for="inlineFormCustomSelectPref">Course Certifier</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><span
                                                        class="fas fa-book-open"></span></span>
                                            </div>
                                            <select class="custom-select my-1 mr-sm-2" name="Ccertifier"
                                                id="id_certifier">
                                                <option selected="selected">Choose...</option>
                                                {% for ele in certifier %}
                                                <option value="{{ele.id}}">{{ele.name}}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <!--End of Form-->
                                    <!-- Form -->
                                    <div class="form-group">
                                        <label for="exampleInputIcon4">Course Description</label>
                                        <div class="input-group mb-4">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><span
                                                        class="far fa-file-alt"></span></span>
                                            </div>
                                            <input class="form-control" name="Cdesc" placeholder="Description"
                                                type="text" aria-label="first name" rows="3">
                                        </div>
                                    </div>
                                    <!-- End of Form -->
                            </div>
                            <button type="submit" class="btn btn-block btn-primary">
                                <i class=" fas fa-upload"></i> Publish</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--End of Form Section-->

        <!--Hero section-->
        <div class="section section-header pb-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-lg-8 text-center">
                        <h1 class="display-2 mb-4">Number of Courses Published: {{user.inst_course}}</h1>
                    </div>
                </div>
            </div>
            <!-- End of Hero section -->

            <!--Main Card-->
            <section class="section section-lg pt-0">
                <div class="container">
                    <div class="row">
                        <div class="card-deck">
                            <!-- Profile Card -->
                            {% for course in courses %}
                                <div class="col-12 col-md-6">
                                    <div class="card bg-primary shadow-soft border-light text-center py-4 mb-5">
                                        <div
                                            class="profile-image shadow-inset border border-light bg-primary rounded-circle p-3 mx-auto">
                                            <img src="../../static/images/course.png"
                                                class="card-img-top shadow-soft p-2 border border-light rounded-circle"
                                                alt="Course Image">
                                        </div>
                                        <div class="card-body">
                                            <h3 class="h5 mb-2">{{ course.name}}</h3>
                                            <ul class="list-unstyled justify-content-center mt-3 mb-4"
                                                style=" padding-left:25%; padding-right:25%">
                                                <li>
                                                    <strong>Instructor:</strong> {{ course.instructor.fname}} {{
                                                    course.instructor.lname}}
                                                </li></strong>
                                                <li>
                                                    <strong>Certifier:</strong> {{course.certifier.name}}
                                                </li>
                                                <li>
                                                    <strong>Publish Date:</strong> {{course.publish_date}}
                                                </li>
                                                <li>
                                                    <strong>Description:</strong> {{course.description}}
                                                </li>
                                            </ul>
                                            <a href="/profile/createCourse/{{ course.id }}/"
                                                class="btn btn-primary text-secondary mr-3"><i class="fas fa-trash"></i>
                                                Delete</a>
                                        </div>
                                    </div>
                                </div>
                            {%endfor%}
                            <!-- End of Profile Card -->
                        </div>
                    </div>
                </div>
            </section>
            <!--End of Main Card-->
        </div>
    </main>
    <!-- FOOTER -->
    <footer class="d-flex pb-5 pt-6 pt-md-7 border-top border-light bg-primary">
        <div class="container">
            <div class="col-md-12">
                <div class="nav-wrapper position-relative">
                    <ul class="nav nav-pills nav-fill flex-column flex-md-row">
                        <li class="nav-item"><a class="nav-link mb-sm-3 mb-md-0" href="/">
                                <span class="icon-success">
                                    <span class="fas fa-tachometer-alt mr-2"></span>About Us</span></a>
                        </li>
                        <li class="nav-item"><a class="nav-link mb-sm-3 mb-md-0" href="../../contactUs">
                                <span class="icon-success">
                                    <span class="fas fa-headphones"></span> Contact Us</span></a>
                        </li>
                        <li class="nav-item"><a class="nav-link mb-sm-3 mb-md-0" href="../../termsOfUse">
                                <span class="icon-success">
                                    <span class="fas fa-book-open"></span> Terms And Conditions</span></a>
                        </li>
                    </ul>
                </div>
            </div>
            <hr class="my-5">
            <div class="row">
                <div class="col">
                    <div class="d-flex text-center justify-content-center align-items-center" role="contentinfo">
                        <p class="font-weight-normal font-small mb-0">made with ♥ by Mohammed Sanaullah and Tanmayi D.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- END OF FOOTER -->

    <!-- Core -->
    <script src="../../static/vendor/jquery/dist/jquery.min.js"></script>
    <script src="../../static/vendor/popper.js/dist/umd/popper.min.js"></script>
    <script src="../../static/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="../../static/vendor/headroom.js/dist/headroom.min.js"></script>

    <!-- Vendor JS -->
    <script src="../../static/vendor/onscreen/dist/on-screen.umd.min.js"></script>
    <script src="../../static/vendor/nouislider/distribute/nouislider.min.js"></script>
    <script src="../../static/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="../../static/vendor/waypoints/lib/jquery.waypoints.min.js"></script>
    <script src="../../static/vendor/jarallax/dist/jarallax.min.js"></script>
    <script src="../../static/vendor/jquery.counterup/jquery.counterup.min.js"></script>
    <script src="../../static/vendor/jquery-countdown/dist/jquery.countdown.min.js"></script>
    <script src="../../static/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
    <script src="../../static/vendor/prismjs/prism.js"></script>

    <!-- Neumorphism JS -->
    <script src="../../static/assets/js/neumorphism.js"></script>
</body>




</html>